services:
  grudes_api:
    build:
      context: grudes_api 
      target: dev
    image: grudes_api 
    volumes:
      - ./grudes_api:/app
  grudes_web_client:
    build:
      context: grudes_web_client 
      target: dev
    volumes:
      - ./grudes_web_client:/app
